namespace ZienPaymentSDK.Paypal.Constants
{
    public static class PaypalWebHookConstants
    {
        public const string BILLING_PLAN_ACTIVATED = "BILLING.PLAN.ACTIVATED";
        public const string BILLING_PLAN_CREATED = "BILLING.PLAN.CREATED";
        public const string BILLING_PLAN_DEACTIVATED = "BILLING.PLAN.DEACTIVATED";
        public const string BILLING_PLAN_PRICINGCHANGE_ACTIVATED = "BILLING.PLAN.PRICING-CHANGE.ACTIVATED";
        public const string BILLING_PLAN_UPDATED = "BILLING.PLAN.UPDATED";
        public const string BILLING_SUBSCRIPTION_ACTIVATED = "BILLING.SUBSCRIPTION.ACTIVATED";
        public const string BILLING_SUBSCRIPTION_CANCELLED = "BILLING.SUBSCRIPTION.CANCELLED";
        public const string BILLING_SUBSCRIPTION_CREATED = "BILLING.SUBSCRIPTION.CREATED";
        public const string BILLING_SUBSCRIPTION_EXPIRED = "BILLING.SUBSCRIPTION.EXPIRED";
        public const string BILLING_SUBSCRIPTION_PAYMENT_FAILED = "BILLING.SUBSCRIPTION.PAYMENT.FAILED";
        public const string BILLING_SUBSCRIPTION_REACTIVATED = "BILLING.SUBSCRIPTION.RE-ACTIVATED";
        public const string BILLING_SUBSCRIPTION_SUSPENDED = "BILLING.SUBSCRIPTION.SUSPENDED";
        public const string BILLING_SUBSCRIPTION_UPDATED = "BILLING.SUBSCRIPTION.UPDATED";
        public const string BILLING_AGREEMENTS_AGREEMENT_CANCELLED = "BILLING_AGREEMENTS.AGREEMENT.CANCELLED";
        public const string BILLING_AGREEMENTS_AGREEMENT_CREATED = "BILLING_AGREEMENTS.AGREEMENT.CREATED";
        public const string CATALOG_PRODUCT_CREATED = "CATALOG.PRODUCT.CREATED";
        public const string CATALOG_PRODUCT_UPDATED = "CATALOG.PRODUCT.UPDATED";
        public const string CHECKOUT_CHECKOUT_BUYERAPPROVED = "CHECKOUT.CHECKOUT.BUYER-APPROVED";
        public const string CHECKOUT_ORDER_APPROVED = "CHECKOUT.ORDER.APPROVED";
        public const string CHECKOUT_ORDER_COMPLETED = "CHECKOUT.ORDER.COMPLETED";
        public const string CHECKOUT_ORDER_PROCESSED = "CHECKOUT.ORDER.PROCESSED";
        public const string CUSTOMER_ACCOUNTLIMITATION_ADDED = "CUSTOMER.ACCOUNT-LIMITATION.ADDED";
        public const string CUSTOMER_ACCOUNTLIMITATION_ESCALATED = "CUSTOMER.ACCOUNT-LIMITATION.ESCALATED";
        public const string CUSTOMER_ACCOUNTLIMITATION_LIFTED = "CUSTOMER.ACCOUNT-LIMITATION.LIFTED";
        public const string CUSTOMER_ACCOUNTLIMITATION_UPDATED = "CUSTOMER.ACCOUNT-LIMITATION.UPDATED";
        public const string CUSTOMER_DISPUTE_CREATED = "CUSTOMER.DISPUTE.CREATED";
        public const string CUSTOMER_DISPUTE_RESOLVED = "CUSTOMER.DISPUTE.RESOLVED";
        public const string CUSTOMER_DISPUTE_UPDATED = "CUSTOMER.DISPUTE.UPDATED";
        public const string CUSTOMER_MERCHANTINTEGRATION_CAPABILITYUPDATED = "CUSTOMER.MERCHANT-INTEGRATION.CAPABILITY-UPDATED";
        public const string CUSTOMER_MERCHANTINTEGRATION_PRODUCTSUBSCRIPTIONUPDATED = "CUSTOMER.MERCHANT-INTEGRATION.PRODUCT-SUBSCRIPTION-UPDATED";
        public const string CUSTOMER_MERCHANTINTEGRATION_SELLERALREADYINTEGRATED = "CUSTOMER.MERCHANT-INTEGRATION.SELLER-ALREADY-INTEGRATED";
        public const string CUSTOMER_MERCHANTINTEGRATION_SELLERCONSENTGRANTED = "CUSTOMER.MERCHANT-INTEGRATION.SELLER-CONSENT-GRANTED";
        public const string CUSTOMER_MERCHANTINTEGRATION_SELLEREMAILCONFIRMED = "CUSTOMER.MERCHANT-INTEGRATION.SELLER-EMAIL-CONFIRMED";
        public const string CUSTOMER_MERCHANTINTEGRATION_SELLERONBOARDINGINITIATED = "CUSTOMER.MERCHANT-INTEGRATION.SELLER-ONBOARDING-INITIATED";
        public const string IDENTITY_AUTHORIZATIONCONSENT_REVOKED = "IDENTITY.AUTHORIZATION-CONSENT.REVOKED";
        public const string INVOICING_INVOICE_CANCELLED = "INVOICING.INVOICE.CANCELLED";
        public const string INVOICING_INVOICE_CREATED = "INVOICING.INVOICE.CREATED";
        public const string INVOICING_INVOICE_PAID = "INVOICING.INVOICE.PAID";
        public const string INVOICING_INVOICE_REFUNDED = "INVOICING.INVOICE.REFUNDED";
        public const string INVOICING_INVOICE_SCHEDULED = "INVOICING.INVOICE.SCHEDULED";
        public const string INVOICING_INVOICE_UPDATED = "INVOICING.INVOICE.UPDATED";
        public const string MERCHANT_ONBOARDING_COMPLETED = "MERCHANT.ONBOARDING.COMPLETED";
        public const string MERCHANT_PARTNERCONSENT_REVOKED = "MERCHANT.PARTNER-CONSENT.REVOKED";
        public const string PAYMENT_AUTHORIZATION_CREATED = "PAYMENT.AUTHORIZATION.CREATED";
        public const string PAYMENT_AUTHORIZATION_VOIDED = "PAYMENT.AUTHORIZATION.VOIDED";
        public const string PAYMENT_CAPTURE_COMPLETED = "PAYMENT.CAPTURE.COMPLETED";
        public const string PAYMENT_CAPTURE_DENIED = "PAYMENT.CAPTURE.DENIED";
        public const string PAYMENT_CAPTURE_PENDING = "PAYMENT.CAPTURE.PENDING";
        public const string PAYMENT_CAPTURE_REFUNDED = "PAYMENT.CAPTURE.REFUNDED";
        public const string PAYMENT_CAPTURE_REVERSED = "PAYMENT.CAPTURE.REVERSED";
        public const string PAYMENT_ORDER_CANCELLED = "PAYMENT.ORDER.CANCELLED";
        public const string PAYMENT_ORDER_CREATED = "PAYMENT.ORDER.CREATED";
        public const string PAYMENT_PAYOUTSITEM_BLOCKED = "PAYMENT.PAYOUTS-ITEM.BLOCKED";
        public const string PAYMENT_PAYOUTSITEM_CANCELED = "PAYMENT.PAYOUTS-ITEM.CANCELED";
        public const string PAYMENT_PAYOUTSITEM_DENIED = "PAYMENT.PAYOUTS-ITEM.DENIED";
        public const string PAYMENT_PAYOUTSITEM_FAILED = "PAYMENT.PAYOUTS-ITEM.FAILED";
        public const string PAYMENT_PAYOUTSITEM_HELD = "PAYMENT.PAYOUTS-ITEM.HELD";
        public const string PAYMENT_PAYOUTSITEM_REFUNDED = "PAYMENT.PAYOUTS-ITEM.REFUNDED";
        public const string PAYMENT_PAYOUTSITEM_RETURNED = "PAYMENT.PAYOUTS-ITEM.RETURNED";
        public const string PAYMENT_PAYOUTSITEM_SUCCEEDED = "PAYMENT.PAYOUTS-ITEM.SUCCEEDED";
        public const string PAYMENT_PAYOUTSITEM_UNCLAIMED = "PAYMENT.PAYOUTS-ITEM.UNCLAIMED";
        public const string PAYMENT_PAYOUTSBATCH_DENIED = "PAYMENT.PAYOUTSBATCH.DENIED";
        public const string PAYMENT_PAYOUTSBATCH_PROCESSING = "PAYMENT.PAYOUTSBATCH.PROCESSING";
        public const string PAYMENT_PAYOUTSBATCH_SUCCESS = "PAYMENT.PAYOUTSBATCH.SUCCESS";
        public const string PAYMENT_REFERENCEDPAYOUTITEM_COMPLETE = "PAYMENT.REFERENCED-PAYOUT-ITEM.COMPLETE";
        public const string PAYMENT_REFERENCEDPAYOUTITEM_COMPLETED = "PAYMENT.REFERENCED-PAYOUT-ITEM.COMPLETED";
        public const string PAYMENT_REFERENCEDPAYOUTITEM_FAILED = "PAYMENT.REFERENCED-PAYOUT-ITEM.FAILED";
        public const string PAYMENT_SALE_COMPLETED = "PAYMENT.SALE.COMPLETED";
        public const string PAYMENT_SALE_DENIED = "PAYMENT.SALE.DENIED";
        public const string PAYMENT_SALE_PENDING = "PAYMENT.SALE.PENDING";
        public const string PAYMENT_SALE_REFUNDED = "PAYMENT.SALE.REFUNDED";
        public const string PAYMENT_SALE_REVERSED = "PAYMENT.SALE.REVERSED";
        public const string PAYMENTS_PAYMENT_CREATED = "PAYMENTS.PAYMENT.CREATED";
        public const string RISK_DISPUTE_CREATED = "RISK.DISPUTE.CREATED";
        public const string VAULT_CREDITCARD_CREATED = "VAULT.CREDIT-CARD.CREATED";
        public const string VAULT_CREDITCARD_DELETED = "VAULT.CREDIT-CARD.DELETED";
        public const string VAULT_CREDITCARD_UPDATED = "VAULT.CREDIT-CARD.UPDATED";


        public const string BILLING_SUBSCRIPTION_Prefix = "BILLING.SUBSCRIPTION";
        public const string PAYMENT_SALE_Prefix = "PAYMENT.SALE";
        public const string INVOICING_INVOICE_Prefix = "INVOICING.INVOICE";
        public const string CHECKOUT_ORDER_Prefix = "CHECKOUT.ORDER";

    }

}

